-- Add scenes column to stories table for AI-generated image prompts
-- This column will store the image prompts generated by the story AI
-- including character description and prompts for cover, scenes, and closing

ALTER TABLE public.stories 
ADD COLUMN scenes jsonb NULL;

-- Add GIN index for better query performance on scenes JSON column
CREATE INDEX idx_stories_scenes ON public.stories USING gin(scenes);

-- Add comment explaining the structure
COMMENT ON COLUMN public.stories.scenes IS 'JSON structure containing AI-generated prompts for images: {character, cover, scene_1, scene_2, scene_3, scene_4, closing}. Generated by the story AI to ensure visual consistency across all images.';

